defaults: &defaults
#  job_temp_dir: '/tmp' # uses system temp dir by default
  identifier_template: 'ta.reeddeeddk'
  identifier_statefile: '/tmp/trifle-minter-state'
  image_convert_command: ['scripts/convert_ptif.sh']
#  image_convert_command: ['scripts/convert_jp2.sh']
  image_convert_format: 'ptif'
#  image_convert_format: 'jp2'
  fits_path: '/home/qgkb58/hydra/fits-0.8.6/fits.sh'

development:
  <<: *defaults
  ark_naan: '12345'
  # url to image server
  image_server_url: 'http://localhost/iipsrv/iipsrv.fcgi' 
  # url to image server with IIIF protocol
  image_service_url: 'http://localhost/iipsrv/iipsrv.fcgi?IIIF=' 
  # host used in IIIF manifest files for resources, should ideally be same as rails application host
  iiif_host: 'http://localhost:3000' 
  # location for manifests in mirador manifest list
  mirador_location: 'Durham University' 
  # base url where mirador viewer can be found
  mirador_base_url: 'http://localhost/mirador/' 
  # settings for uploading iiif and images to image server
  image_server_config:
    host: 'localhost'
    user: <%= ENV['USER'] %>
    iiif_root: <%= File.join(Dir.home,'mock_iiif') %>/
    images_root: <%= File.join(Dir.home,'iipimages') %>/

test:
  <<: *defaults

production:
  <<: *defaults
